### ISSUE TITLE
Installing from GitHub doesn't work

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#114]
It seems to have something to do with how you are reading in the version of package during install

```bash
(develop)vagrant@vagrant-ubuntu-trusty-64:~$ pip install https://github.com/SciLifeLab/genologics/tarball/master
Collecting https://github.com/SciLifeLab/genologics/tarball/master
  Downloading https://github.com/SciLifeLab/genologics/tarball/master
     / 65kB 351kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-RMxJwu-build/setup.py", line 13, in <module>
        with open(version_py, 'r') as fh:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-RMxJwu-build/version.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-RMxJwu-build
```

**Comment by Galithil** [comment]
Impossible to reproduce, either by me or @robinandeer.
