### ISSUE TITLE
Should "required" empty fields crash the client?

### ISSUE THREAD

**Issue by brainstorm** [SciLifeLab/genologics#4]
@pekrau, Validations are a bit too stringent?:

https://github.com/SciLifeLab/genologics/blob/master/genologics/lims.py#L100

```
$ python examples/attach_delivery_report.py

Traceback (most recent call last):
  File "attach_delivery_report.py", line 31, in <module>
    project.put()
  File "/Users/roman/.virtualenvs/genologics/lib/python2.7/site-packages/genologics-0.2-py2.7.egg/genologics/entities.py", line 492, in put
    self.lims.put(self.uri, data)
  File "/Users/roman/.virtualenvs/genologics/lib/python2.7/site-packages/genologics-0.2-py2.7.egg/genologics/lims.py", line 62, in put
    return self.parse_response(r)
  File "/Users/roman/.virtualenvs/genologics/lib/python2.7/site-packages/genologics-0.2-py2.7.egg/genologics/lims.py", line 100, in parse_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 400: Invalid project. Portal ID is a required field and must have a value
```

**Comment by Galithil** [comment]
The lims will not accept the new data, and throwing our errors seems like the right way to work. They can always be properly handled downstream.
